/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: OneSteven (https://sketchfab.com/Steven007)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/tesla-model-s-1360e3cf7323487eaba8ce94279229b6
title: Tesla Model S
*/

import React, { useRef, useEffect, useState, Suspense } from 'react';
import { useGLTF } from '@react-three/drei';
import { useThree } from '@react-three/fiber';
import * as THREE from 'three'
import { useSpring } from '@react-spring/three';
import { useControls } from '../../Context/controlsContext';
import { OrbitControls } from "@react-three/drei";
import { CarAudio } from './CarAudio';

const DEFAULT_LAYER = 0
const OCCLUSION_LAYER = 1

export default function Model(props) {
    const group = useRef()
    const controls = useRef();
    const ref = useRef(null);
    const { nodes, materials } = useGLTF('/car/scene.gltf')
    const [path, setPath] = useState(null);
    const { gl: renderer, camera, scene, clock } = useThree();

    const { bloom } = props;

    const {
        activeObject,
        setActiveObject,
        setActiveObjectName,
        activeObjectName,
        setNodes,
        setBloomRef
    } = useControls(state => ({
        setActiveObject: state.setActiveObject,
        activeObject: state.activeObject,
        setActiveObjectName: state.setActiveObjectName,
        activeObjectName: state.activeObjectName,
        setNodes: state.setNodes,
        setBloomRef: state.setBloomRef
    }));

    const [initialPosition, setInitialPosition] = useState(camera.position);

    useEffect(() => {
        setBloomRef(group);
    }, [])

    useEffect(() => {
        if (nodes) {
            setNodes(nodes);
        }

        function onPositionChange(o) {
            if (controls.current.enabled) {
                setInitialPosition(camera.position)
                console.log("position changed in object");
            }
        }

        if (controls.current) {
            controls.current.addEventListener('change', onPositionChange);
        }
    }, []);

    useSpring({
        config: { duration: activeObject ? 2000 : 0, clamp: true, precision: 1 },
        percentage: activeObject ? 1 : 0,
        onChange: (
            { value: { percentage } }
        ) => {
            if (percentage > 0) {
                // percentage = Math.round(percent)
                controls.current.enabled = false;
                const start = initialPosition;
                // console.log({ initialPosition })
                console.log({ percentage })
                // nodes[activeObjectName].scale = new THREE.Vector3(0.01, 0.01, 0.01)
                const end = nodes[activeObjectName].position;

                // console.log({ end })
                const endCloned = end;
                let endScaled = new THREE.Vector3(endCloned.x, endCloned.y, endCloned.z);
                endScaled = endScaled.multiplyScalar(0.01)

                camera.lookAt(endScaled)
                endScaled.x = endScaled.x + endScaled.x + endScaled.x + endScaled.x;
                // endScaled.z = endScaled.z + endScaled.z;

                const scalarVector = endScaled;


                const lerpedVector = new THREE.Vector3()
                lerpedVector.lerpVectors(start, scalarVector, percentage / 10)
                camera.position.z = lerpedVector.z;
                camera.position.x = lerpedVector.x;
                camera.position.y = lerpedVector.y;


            }
        },
        onStart: () => {
            controls.current.enabled = false;
        },
        onRest: () => {





            const start = initialPosition;
            // console.log({ nodes })
            // nodes[activeObjectName].scale = new THREE.Vector3(0.01, 0.01, 0.01)
            const end = nodes[activeObjectName].position;

            // console.log({ end })
            const endCloned = end;
            let endScaled = new THREE.Vector3(endCloned.x, endCloned.y, endCloned.z);
            endScaled = endScaled.multiplyScalar(0.01)

            controls.current.enabled = true;
            controls.current.target = endScaled;
            setActiveObject(false);
        },
    });

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="OSG_Scene">
                <axesHelper args={[5]} />
                <OrbitControls
                    ref={controls}
                    position={[0, 5, 10]}
                // maxAzimuthAngle={Math.PI / 2}
                // maxPolarAngle={Math.PI / 3}
                // minAzimuthAngle={-Math.PI / 2}
                // minPolarAngle={Math.PI / 3}
                // minDistance={1}
                // maxDistance={7}
                />

                <group
                    name="RootNode_(gltf_orientation_matrix)"
                    scale={[0.01, 0.01, 0.01]}
                    rotation={[-Math.PI / 2, 0, 0]}
                >
                    <group name="RootNode_(model_correction_matrix)">
                        <group name="Tesla_Model_Sfbx" rotation={[Math.PI / 2, 0, 0]}>
                            <group name="RootNode">
                                <group
                                    name="wheel003"
                                    position={[94.06, 24.63, -179.13]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={1.22}
                                >
                                    <mesh
                                        name="wheel003_Material007_0"
                                        layers={1}
                                        geometry={nodes.wheel003_Material007_0.geometry}
                                        material={nodes.wheel003_Material007_0.material}
                                    />

                                    <mesh
                                        name="wheel003_Material006_0"
                                        layers={1}
                                        geometry={nodes.wheel003_Material006_0.geometry}
                                        material={nodes.wheel003_Material006_0.material}
                                    />
                                    <mesh
                                        name="wheel003_Rims_0"
                                        layers={1}
                                        geometry={nodes.wheel003_Rims_0.geometry}
                                        material={nodes.wheel003_Rims_0.material}
                                    />
                                </group>
                                <group
                                    name="cal003"
                                    position={[94.06, 24.63, -179.13]}
                                    rotation={[0.28, 0, 0]}
                                    scale={[1.08, 1.08, 1.08]}
                                >
                                    <mesh
                                        name="cal003_Material008_0"
                                        layers={1}
                                        geometry={nodes.cal003_Material008_0.geometry}
                                        material={nodes.cal003_Material008_0.material}
                                    />
                                </group>
                                <group
                                    name="wheel002"
                                    position={[-94.06, 24.63, -179.13]}
                                    rotation={[-Math.PI / 2, 0, -Math.PI]}
                                    scale={1.22}
                                >
                                    <mesh
                                        name="wheel002_Material007_0"
                                        layers={1}
                                        geometry={nodes.wheel002_Material007_0.geometry}
                                        material={nodes.wheel002_Material007_0.material}
                                    />
                                    <mesh
                                        name="wheel002_Material006_0"
                                        layers={1}
                                        geometry={nodes.wheel002_Material006_0.geometry}
                                        material={nodes.wheel002_Material006_0.material}
                                    />
                                    <mesh
                                        name="wheel002_Rims_0"
                                        layers={1}
                                        geometry={nodes.wheel002_Rims_0.geometry}
                                        material={nodes.wheel002_Rims_0.material}
                                    />
                                </group>
                                <group
                                    name="cal002"
                                    position={[-94.06, 24.63, -179.13]}
                                    rotation={[0.28, 0, 0]}
                                    scale={[-1.08, 1.08, 1.08]}
                                >
                                    <mesh
                                        name="cal002_Material008_0"
                                        layers={1}
                                        geometry={nodes.cal002_Material008_0.geometry}
                                        material={nodes.cal002_Material008_0.material}
                                    />
                                </group>
                                <group
                                    name="cal001"
                                    position={[-94.06, 24.63, 153.98]}
                                    rotation={[2.86, 0.3, 0.09]}
                                    scale={[-1.08, 1.08, 1.08]}
                                >
                                    <mesh
                                        name="cal001_Material008_0"
                                        layers={1}
                                        geometry={nodes.cal001_Material008_0.geometry}
                                        material={nodes.cal001_Material008_0.material}
                                    />
                                </group>
                                <group
                                    name="wheel001"
                                    position={[-94.06, 24.63, 153.98]}
                                    rotation={[-Math.PI / 2, 0, 2.83]}
                                    scale={[1.22, 1.22, 1.22]}
                                >
                                    <mesh
                                        name="wheel001_Material007_0"
                                        layers={1}
                                        geometry={nodes.wheel001_Material007_0.geometry}
                                        material={nodes.wheel001_Material007_0.material}
                                    />
                                    <mesh
                                        name="wheel001_Material006_0"
                                        layers={1}
                                        geometry={nodes.wheel001_Material006_0.geometry}
                                        material={nodes.wheel001_Material006_0.material}
                                    />
                                    <mesh
                                        name="wheel001_Rims_0"
                                        layers={1}
                                        geometry={nodes.wheel001_Rims_0.geometry}
                                        material={nodes.wheel001_Rims_0.material}
                                    />
                                </group>
                                <group name="object" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        layers={1}
                                        name="object_emit_0"
                                        geometry={nodes.object_emit_0.geometry}
                                        material={materials.emit}
                                    />
                                </group>
                                <group name="object001" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object001_int_0"
                                        layers={1}
                                        geometry={nodes.object001_int_0.geometry}
                                        material={materials.material}
                                    />
                                </group>

                                <group name="object002" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object002_red_0"
                                        layers={1}
                                        geometry={nodes.object002_red_0.geometry}
                                        material={materials.material_6}
                                    />
                                </group>
                                <group name="object003" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object003_Material004_0"
                                        layers={1}
                                        geometry={nodes.object003_Material004_0.geometry}
                                        material={materials["Material.004"]}
                                    />
                                </group>
                                <group name="object004" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object004_glack_0"
                                        layers={1}
                                        geometry={nodes.object004_glack_0.geometry}
                                        material={materials.glack}
                                    />
                                </group>
                                <group name="object005" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object005_bod_0"
                                        layers={1}
                                        geometry={nodes.object005_bod_0.geometry}
                                        material={materials.material_9}
                                    />
                                </group>
                                <group name="object006" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object006_chr_0"
                                        layers={1}
                                        geometry={nodes.object006_chr_0.geometry}
                                        material={materials.material_10}
                                    />
                                </group>
                                <group name="object007" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object007_flack_0"
                                        layers={1}
                                        geometry={nodes.object007_flack_0.geometry}
                                        material={materials.flack}
                                    />
                                </group>
                                <group name="object008" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object008_Material002_0"
                                        layers={1}
                                        geometry={nodes.object008_Material002_0.geometry}
                                        material={materials["Material.002"]}
                                    />
                                </group>
                                <group name="object009" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object009_Material005_0"
                                        layers={1}
                                        geometry={nodes.object009_Material005_0.geometry}
                                        material={materials["Material.005"]}
                                    />
                                </group>
                                <group ref={ref} name="object010" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object010_glass_0"
                                        layers={2}
                                        geometry={nodes.object010_glass_0.geometry}
                                    // material={materials.glass}
                                    >
                                        <meshStandardMaterial attach="material" color="white" />
                                    </mesh>
                                </group>
                                <group name="object012" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object012_Material001_0"
                                        layers={1}
                                        geometry={nodes.object012_Material001_0.geometry}
                                        material={materials["Material.001"]}
                                    />
                                </group>
                                <group name="object013" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object013_grill_0"
                                        layers={1}
                                        geometry={nodes.object013_grill_0.geometry}
                                        material={materials.grill}
                                    />
                                </group>
                                <group name="object014" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object014_Material003_0"
                                        layers={1}
                                        geometry={nodes.object014_Material003_0.geometry}
                                        material={materials["Material.003"]}
                                    />
                                </group>
                                <group name="object015" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        name="object015_rev_0"
                                        layers={1}
                                        geometry={nodes.object015_rev_0.geometry}
                                        material={materials.material_18}
                                    />
                                </group>
                                <group name="object016" scale={[0.1, 0.1, 0.1]}>
                                    <mesh
                                        layers={1}
                                        e="object016_refl_0"
                                        geometry={nodes.object016_refl_0.geometry}
                                        material={materials.refl}
                                    />
                                </group>
                                <group
                                    name="cal"
                                    position={[94.06, 24.63, 153.98]}
                                    rotation={[2.86, 0.3, 0.09]}
                                    scale={1.08}
                                >
                                    <mesh
                                        name="cal_Material008_0"
                                        layers={1}
                                        geometry={nodes.cal_Material008_0.geometry}
                                        material={nodes.cal_Material008_0.material}
                                    />
                                </group>
                                <group
                                    name="wheel"
                                    position={[94.06, 24.63, 153.98]}
                                    rotation={[-Math.PI / 2, 0, -Math.PI / 10]}
                                    scale={[1.22, 1.22, 1.22]}
                                >
                                    <mesh
                                        name="wheel_Material007_0"
                                        layers={1}
                                        geometry={nodes.wheel_Material007_0.geometry}
                                        material={nodes.wheel_Material007_0.material}
                                    />
                                    <mesh
                                        name="wheel_Material006_0"
                                        layers={1}
                                        geometry={nodes.wheel_Material006_0.geometry}
                                        material={nodes.wheel_Material006_0.material}
                                    />
                                    <mesh
                                        name="wheel_Rims_0"
                                        layers={1}
                                        geometry={nodes.wheel_Rims_0.geometry}
                                        material={nodes.wheel_Rims_0.material}
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/scene.gltf");
